### ISSUE TITLE
DS store may go

### ISSUE THREAD

**Issue by kghbln** [TobiasWeller/SemanticTextAnnotator#2]
I guess the DS store file may go

**Comment by TobiasWeller** [comment]
Ok., Thanks. I deleted it.

**Comment by kghbln** [comment]
Thanks. I guess this is some OSX specific superfluous stuff. This file is acutally in all the other extensions too.

**Comment by TobiasWeller** [comment]
Ok., I'll delete it in the other ones, too.

**Comment by kghbln** [comment]
Cool
