### ISSUE TITLE
Not working on 1.28.2 

### ISSUE THREAD

**Issue by Ilja-developer** [TobiasWeller/SemanticTextAnnotator#3]
Hi There,

Installed it on version 1.28.2 and get 2 signs:

1. - Notice:  Use of undefined constant PF_NS_FORM - assumed 'PF_NS_FORM' in .\extensions\SemanticTextAnnotator\SemanticTextAnnotator.hooks.php on line 45
2. - Warning:  Parameter 1 to SemanticTextAnnotatorHooks::onBeforePageDisplay() expected to be a reference, value given in .\includes\Hooks.php on line 195

Any ideas?

**Comment by TobiasWeller** [comment]
Hey,
I tested it on version 1.28.2 and did not get any error. Did you install PageForms?...because this is a prerequisite of Semantic Text Annotator (as well as Semantic MediaWiki) (an probably the issue of 1.) 

Cheers
Tobi

**Comment by Ilja-developer** [comment]
Hi!

Thanks so much for the quick reply. I'm totally new to Media wiki. So if I understand correctly I install MediaWiki, then SemanticWiki, then PageForms and then this extension? 

Again, many thanks seems like an amazing extension.

Ilja

**Comment by TobiasWeller** [comment]
Hello Ilja,

yes exactly.
* Install [Mediawiki](https://www.mediawiki.org/wiki/MediaWiki)
* Install [Semantic MediaWiki](https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.25%2B)
* Install [PageForms](https://github.com/wikimedia/mediawiki-extensions-PageForms/archive/master.tar.gz)

And then install Semantic Text Annotator.


Cheers
Tobi

**Comment by Ilja-developer** [comment]
Hi Tobias,

No luck here :( 

Did it exactly as you said and get these errors: 

1. Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in ..\includes\Hooks.php on line 195
2. Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in ..\includes\Hooks.php on line 195
3. Warning:  Parameter 1 to SemanticTextAnnotatorHooks::onBeforePageDisplay() expected to be a reference, value given in ..\includes\Hooks.php on line 195
4. Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in ..\includes\Hooks.php on line 195

MediaWiki	1.28.2
PHP	                7.1.4 (apache2handler)
MariaDB	        10.1.22-MariaDB

So sad it looks so amazing and all..

**Comment by TobiasWeller** [comment]
Hey Ilja,
Thanks for the infos. I guess it's because of your PHP Version. MediaWiki Version 1.28.2 is not compatible with PHP 7.1.4.

> Please note that MediaWiki is not yet fully compatible with PHP 7.1... [1]

I would recommend to use PHP version 7.0.12. At least I used this version for testing and it worked.


Cheers
Tobi

[1] https://www.mediawiki.org/wiki/Compatibility#PHP

**Comment by Ilja-developer** [comment]
Hi Tobias,

Ah thats sucks! Thanks so much for the reply. Seems like an great extra!

**Comment by TobiasWeller** [comment]
You closed the thread, so I guess it works?!
Thank you :)

**Comment by Ilja-developer** [comment]
No, my server runs on the newest PHP so I can't test it. I now use https://web.hypothes.is/.
