### ISSUE TITLE
Anon user is allowed to annotate

### ISSUE THREAD

**Issue by mwjames** [TobiasWeller/SemanticTextAnnotator#5]
Testing [0] as anon user which still lets me try to save comments even though it is disallowed for this user group.

![image](https://cloud.githubusercontent.com/assets/1245473/26761413/8772cf86-4969-11e7-9aca-a20cac26785b.png)

[0] https://sandbox.semantic-mediawiki.org/wiki/Do,_Jane#

**Comment by TobiasWeller** [comment]
Hey,
ok., thanks. I haven't had this on my list. I now disallow to create annotations If user has no rights to edit/create pages.

Cheers
Tobi
