### ISSUE TITLE
Anon user can alter Special:SemanticTextAnnotator

### ISSUE THREAD

**Issue by mwjames** [TobiasWeller/SemanticTextAnnotator#6]
https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:SemanticTextAnnotator

![image](https://cloud.githubusercontent.com/assets/1245473/26761467/fb990b68-496a-11e7-9e90-c7e578cd03bf.png)

**Comment by TobiasWeller** [comment]
Ok., I changed it, so only sysops users can access this Special Page.
I will add some more information in order to explain the progress (likewise the Semantic Image Annotator).

Cheers
Tobi
